### PR TITLE
Finish up SysEx implementation

### PR DESCRIPTION
**Pull request by mat1jaczyyy**
This change ensures the data is handled properly via Tests.

### CODE REVIEW

**Comment by mat1jaczyyy** [comment]
The only merge conflict was a code style change in StructHelper. I've implemented your styling along with the removed unnecessary check.

**Comment by micdah** [comment]
Great - just give me a ping when you think it's ready for merging and deploy 😄

**Comment by mat1jaczyyy** [comment]
@micdah It's ready unless you want to make any additional changes.

**Comment by micdah** [comment]
Excellent, I'll create release 1.0.48

**Comment by mat1jaczyyy** [comment]
Cool, now I can switch back to the NuGet package instead of relying on a custom build. Thanks!

**Comment by micdah** [comment]
It's deployed, and available on nuget.org: https://www.nuget.org/packages/RtMidi.Core/1.0.48 👍

**Pull request merged**
